network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      dhcp4: yes
  bridges:
    br0:
      interfaces: [eno1]
      dhcp4: no
      addresses: [192.168.1.10/24]
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.1.1
